### ISSUE TITLE
Feature request: Multi select

### ISSUE THREAD

**Issue by isaacplmann** [vlio20/ng2-date-picker#11]
I'd like to be able to select multiple dates on a `<dp-calendar>`.  If you're interested in this feature, I can work on a pr.

**Comment by vlio20** [comment]
@isaacplmann, this would be great! 
The number of selections should be configurable : 
Default : 1 
Also there should be configuration for min and max selection. 
There also should be an option to put infinite number of selections.

**Comment by isaacplmann** [comment]
I can't seem to build the library.  When I run `npm i && npm start` I get the following errors:

```
ERROR in [default] /.../ng2-date-picker/node_modules/@types/jasmine/index.d.ts:39:37
A parameter initializer is only allowed in a function or constructor implementation.

ERROR in [default] /.../ng2-date-picker/node_modules/@types/jasmine/index.d.ts:39:45
Cannot find name 'keyof'.

ERROR in [default] /.../ng2-date-picker/node_modules/@types/jasmine/index.d.ts:39:51
'=' expected.
```

**Comment by isaacplmann** [comment]
Wait - I think it did build.  It just shows those errors every time.  I'll just ignore them and see how far I get.

**Comment by isaacplmann** [comment]
Making some progress.  I'll probably have a PR ready for discussion on Monday.

1. I'm changing the dp-day-picker value from a `Moment` type to a `Moment[]` type and working through all the functions to make them work with an array.

2. I'm exposing the dp-calendar as a stand alone component

3. I'd like to create a dp-calendar-container component and expose that as well (to handle multiple dp-calendars side by side).

4. I haven't thought about the configuration options for min/max selections yet.

**Comment by vlio20** [comment]
1. It also should support String[] as it can be provided as a String.
2. ok.
3. What would be the API of the container? Not sure why we need it.
4. That can be added later.

**Comment by isaacplmann** [comment]
I haven't thought through the api of the container all the way, but I want a way to be able to show the calendar picker inline all the time (rather than showing it in a popup).  The calendar container seems like a natural way to do that.

**Comment by isaacplmann** [comment]
Similar to the inline mode for [mydatepicker](http://kekeh.github.io/mydatepicker/)

**Comment by vlio20** [comment]
Seems like we can use the calendar component. Not sure why we need the container.

**Comment by isaacplmann** [comment]
The container has the navigation buttons and has the logic to show multiple calendars at once and keep them in sync.

**Comment by vlio20** [comment]
Make sense. Maybe we should move it (the navigation) inside the calendar

**Comment by isaacplmann** [comment]
And allow for multiple months to be shown at once inside the calendar?  That seems like it makes sense in a calendar container component, but I'm happy to move that logic wherever you want.

**Comment by isaacplmann** [comment]
Maybe the inline piece should be a separate PR anyway.  I'm almost done with the multiselect feature - working on tests now.

**Comment by vlio20** [comment]
Greater. 
So you are not including the container in this PR,  Right?

**Comment by isaacplmann** [comment]
Correct.  I'll make a separate PR for the calendar container component.

**Comment by vlio20** [comment]
Let's discuss this in an other thread then

**Comment by isaacplmann** [comment]
I have tests written and there are no typescript errors in them but they won't run because of the errors I mentioned above.  

```
ERROR in [default] /Users/isaac/Documents/Contributions/ng2-date-picker/node_modules/@types/jasmine/index.d.ts:39:37
A parameter initializer is only allowed in a function or constructor implementation.

ERROR in [default] /Users/isaac/Documents/Contributions/ng2-date-picker/node_modules/@types/jasmine/index.d.ts:39:45
Cannot find name 'keyof'.

ERROR in [default] /Users/isaac/Documents/Contributions/ng2-date-picker/node_modules/@types/jasmine/index.d.ts:39:51
'=' expected.
```

Any ideas on how to fix these?

**Comment by vlio20** [comment]
I think there is an option to exclude errors in tsconfig which exists in libs. Let me check.

**Comment by vlio20** [comment]
Try to set skipLibCheck to true in tsconfig

**Comment by isaacplmann** [comment]
Got it to work by pinning the `@types/jasmine` dependency to the version number you had.  (The latest version of @types/jasmine was depending on typescript 2.2.1.

I also needed to add a mime configuration to karma.conf.js per [this comment](https://github.com/angular/angular-cli/issues/2125#issuecomment-247395088) to get the tests to run in Chrome.

I should have a PR posted soon.

**Comment by vlio20** [comment]
Cool! Thanks

**Comment by isaacplmann** [comment]
Running into a bunch of edge cases - I can make it work, but I don't want to create a maintenance nightmare for you so I'm rethinking the design a bit.

**Comment by vlio20** [comment]
OK, let me know if I can help

**Comment by isaacplmann** [comment]
Thanks for merging the PR.

**Comment by vlio20** [comment]
released in 0.3.0. Thanks.

@isaacplmann, are you using the component in production?

**Comment by isaacplmann** [comment]
Not yet but I plan to.

**Comment by vlio20** [comment]
nice!
