### ISSUE TITLE
Feature: Inline DpCalendarContainerComponent

### ISSUE THREAD

**Issue by isaacplmann** [vlio20/ng2-date-picker#16]
I would like the ability to display the calendar picker inline instead of as a popup (not attached to an input text box). [mydatepicker](http://kekeh.github.io/mydatepicker/) has an example of this inline mode, but I would prefer to just use a different component instead of changing a property on the picker.

This could be accomplished by moving functionality into the existing `dp-calendar` component or creating a new `dp-calendar-container` component.  I would lean towards making a new `dp-calendar-container` component, so I'll write out my design with that assumption.

DpCalendarContainerComponent

Inputs:
- selected: Moment[]
- config: ICalendarContainerConfig (a subset of IDayPickerConfig)

Outputs:
- selectedChange: Moment[]
- dayClick: {day: ICalendarDay, event: MouseEvent} (the click event on a given day)
- dayContextMenu: {day: ICalendarDay, event: MouseEvent} (the right-click contextmenu event on a given day)
- calendarMove: {base: Moment, months: number}

Everything in `dp-day-picker` that has to do with the contents of the popup would be moved into the new `dp-calendar-container` component.

What do you think?  Should I start on the PR?

**Comment by vlio20** [comment]
I think it is better to push the navigation inside the calendar this way users could use it instead the container - which adds redundant (as I see it) component.

WDYT?

**Comment by isaacplmann** [comment]
That's fine with me.  So the `dp-calendar` component will be everything inside the popup.  The `dp-day-picker` will be responsible for the input box and opening and closing the popup.

**Comment by vlio20** [comment]
@isaacplmann, yes but it's not that simple. If you will checkout the demo and set more then one calendar (under Amount of Calendars) you will see that there are only 2 arrows. 

So I have a second thought about that, and I think your suggestion is batter.  
Regarding the name `dp-calendar-container` maybe there is a more self-explanatory name...  
WDYT think about `dp-inline-calendar`? other suggestions?

**Comment by isaacplmann** [comment]
If you want it to be more intuitive for people using it, I'd go with `dp-calendar` for the container component and rename the current `dp-calendar` to `dp-month-calendar` or `dp-month`.

**Comment by vlio20** [comment]
sounds good.

**Comment by vlio20** [comment]
added in 4.0.0.
@isaacplmann, thanks!!!
