### ISSUE TITLE
version 0.61 display issues

### ISSUE THREAD

**Issue by samrantmedia** [vlio20/ng2-date-picker#42]
If i click on the input with version 0.6.1 (crreunt version), the date picker module shows  up somewhere completely different on the screen. When I select a date, it displays the time in the input as well as the date. An error also shows up in the console. 

I have reverted to version  0.2.1 and this issue no longer occurs.

**Comment by vlio20** [comment]
This will require some example to work with. Do you have repo so I can investigate?

**Comment by vlio20** [comment]
@samrantmedia, by the way, the latest release is 0.6.2

**Comment by samrantmedia** [comment]
Hi @vlio20 I am using it within a bootstrap version 3 form like so, 

```
  <div class="form-inline row">
    <div class="col-md-12 col-lg-12 date-row">
      <div class="row">
        <div class="col-md-12"><label for="startDate">Start Date</label></div>
      </div>
      <dp-day-picker [(ngModel)]="item.startDate" [class.dp-material]="true" name="startDate" class="datepicker"></dp-day-picker>
    </div>
    <div class="col-md-12 col-lg-12 date-row">
      <div class="row">
        <div class="col-md-12"><label for="endDate">End Date</label></div>
      </div>
      <dp-day-picker [(ngModel)]="item.endDate" [class.dp-material]="true" name="endDate"></dp-day-picker>
    </div>
  </div>
```

Sorry, not able to have time to give a repo at the moment. Feel free to close if it is not easy to replicate.

**Comment by vlio20** [comment]
I will close this for now, will happy to see some example so I can debug it.
