### ISSUE TITLE
add monthNames config.

### ISSUE THREAD

**Issue by lautaros86** [vlio20/ng2-date-picker#45]
Hello, this module is great, but it lacks an option to change the names of months, similar to weekdayNames.

**Comment by vlio20** [comment]
@lautaros86, this is a good point. I will try to push it to the v1 version.

**Comment by vlio20** [comment]
@lautaros86, I almost forgot - you can use `monthFormat` - `monthFormatter`. Let me know if you still struggling with this. Closing for now.
