### ISSUE TITLE
Change Name of Month

### ISSUE THREAD

**Issue by vuhuynh0305** [vlio20/ng2-date-picker#6]
I dont know if you had this option or not. If not can you add more?

**Comment by vlio20** [comment]
@vuhuynh0305, what do you mean by "Change Name of Month"? can you please elaborate?

**Comment by vuhuynh0305** [comment]
you have option "weekdayNames" so I want it for month too.

**Comment by vlio20** [comment]
Nope there is no such feature.

**Comment by vuhuynh0305** [comment]
you mean you don't want to add that option :(

**Comment by vlio20** [comment]
I will, that's why I set this issue as enhancement. Maybe you want to make a PR?

**Comment by vuhuynh0305** [comment]
Thank you :+1:

**Comment by codedoge** [comment]
+1 to this enhancement

**Comment by vlio20** [comment]
@codedoge, @vuhuynh0305, did you saw `monthFormat` configuration option? What other format you require? do you  think it should also have an option to receive a formatter function - which can be passed to the component and it will handle the month formatting?

**Comment by vlio20** [comment]
@codedoge, @vuhuynh0305, please checkout 0.2.0 release (`monthFormatter`) callback function which. This will give you full power of changing the displayed value (month).
