### ISSUE TITLE
Error when trying to use component api

### ISSUE THREAD

**Issue by karolisgrinkevicius** [vlio20/ng2-date-picker#7]
Hi there. I'm using angular 2.2.1 and when I try to use ViewChild according to your given example it throws an error. My component's setup is:

```
import { Component, ViewChild } from '@angular/core';
...
export class ShareComponent {
  @ViewChild('dayPicker') dayPicker: DpDayPickerComponent;

  public openDatePicker(type) {
     this.dayPicker.api.open();
  }
}
```

When I call openDatePicker from template I get an exception:

> error_handler.js:48 EXCEPTION: Error in ./ShareComponent class ShareComponent - inline template:41:10 caused by: Cannot read property 'api' of undefined
ErrorHandler.handleError @ error_handler.js:48
next @ application_ref.js:298
schedulerFn @ async.js:89
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:81
NgZone.triggerError @ ng_zone.js:280
onHandleError @ ng_zone.js:259
ZoneDelegate.handleError @ zone.js:236
Zone.runTask @ zone.js:157
ZoneTask.invoke @ zone.js:335
error_handler.js:50 ORIGINAL EXCEPTION: Cannot read property 'api' of undefined

**Comment by vlio20** [comment]
@karolisgrinkevicius, I updated the demo. Please see if it helps you. if not please create some plunker or demo project so I can test it and try to help.

**Comment by karolisgrinkevicius** [comment]
Where can I find your updated demo?

**Comment by vlio20** [comment]
https://vlio20.github.io/ng2-date-picker/

**Comment by vlio20** [comment]
@karolisgrinkevicius , did it help?

**Comment by vlio20** [comment]
closing this for now.
