### ISSUE TITLE
Add min view option

### ISSUE THREAD

**Issue by vuhuynh0305** [vlio20/ng2-date-picker#9]
0: day
1: month
2: year

**Comment by vlio20** [comment]
@vuhuynh0305, please elaborate. I don't understand your issue/suggestion.

**Comment by vuhuynh0305** [comment]
give the ability to pick based on min view
0: pick day month year
1: pick month year
2: pick year only

**Comment by vlio20** [comment]
Still don't get it. Can you show me an example on other pickers?

**Comment by vuhuynh0305** [comment]
http://bootstrap-datepicker.readthedocs.io/en/latest/options.html#minviewmode

**Comment by vlio20** [comment]
So if I am understanding correctly you would like to change the view to day/month/year etc?

**Comment by vuhuynh0305** [comment]
yup, because I want to pick mm/yyyy only.

**Comment by vlio20** [comment]
This currently out of scope. PR would be nice.

**Comment by vuhuynh0305** [comment]
:(
